# Copyright 2009 Netease Inc. All Rights Reserved.
# Author: tangxiliu@corp.netease.com (Tang Xi Liu)

Import('env')
enet_env = env.Clone()
enet_env.Append(LIBPATH = [
  '$objroot/base',
  '$objroot/thread',
  '$objroot/net',
  '$objroot/util',
  '$objroot/game/auth'])

enet_src = [
  "callbacks.cc",
  "compress.cc",
  "host.cc",
  "list.cc",
  'packet.cc',
  'peer.cc',
  'protocol.cc',
  'unix.cc',
]

enet_env["CCFLAGS"] = r' -g -O2 -fPIC -DPIC -DPACKAGE_NAME=\"libenet\" -DPACKAGE_TARNAME=\"libenet\" -DPACKAGE_VERSION=\"1.3.5\" -DPACKAGE_STRING=\"libenet\ 1.3.5\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"libenet\" -DVERSION=\"1.3.5\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAS_SOCKLEN_T=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAS_GETHOSTBYADDR_R=1 -DHAS_GETHOSTBYNAME_R=1 -DHAS_POLL=1 -DHAS_FCNTL=1 -DHAS_INET_PTON=1 -DHAS_INET_NTOP=1 -DHAS_MSGHDR_FLAGS=1 -DHAS_SOCKLEN_T=1'
#enet_env["CCFLAGS"] = ''
enet_env["CPPFLAGS"] = ''

enet_objs = []
for src in enet_src:
  enet_objs += enet_env.Object(src)

enet_env.StaticLibrary('enet', enet_objs)
